package com.bookstore.entities;// default package
// Generated Aug 24, 2024, 4:07:45 PM by Hibernate Tools 6.5.2.Final


import jakarta.persistence.*;

import java.sql.Date;

/**
 * Admin generated by hbm2java
 */
@Entity
@NamedQueries(
        {
                @NamedQuery(name = "Admin.listAll" , query = "select b from Buyer b order by name"),
                @NamedQuery(name = "Admin.findByEmail" , query = " select b from Buyer b where  b.email = :email"),
                @NamedQuery(name = "Admin.checkLogin" , query = "select b from Buyer b where b.email = :email and b.password = :password" )
        }
)
@Table(name="admin"
    ,catalog="bookstore"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Admin  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String password;
     private Date birthday;
     private String job;
     private String city;
     private String street;
     private String phone;

    public Admin() {
    }

	
    public Admin(int id, String name, String email, String password) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
    }
    public Admin(int id, String name, String email, String password, Date birthday, String job, String city, String street, String phone) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
       this.birthday = birthday;
       this.job = job;
       this.city = city;
       this.street = street;
       this.phone = phone;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", unique=true, nullable=false, length=255)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=255)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="job", length=255)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }

    
    @Column(name="city", length=255)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="street", length=255)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="phone", length=20)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }





}


