package com.bookstore.entities;// default package
// Generated Aug 24, 2024, 4:07:45 PM by Hibernate Tools 6.5.2.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * BuyerInterests generated by hbm2java
 */
@Entity
@Table(name="buyer_interests"
    ,catalog="bookstore"
)
public class BuyerInterests  implements java.io.Serializable {


     private BuyerInterestsId id;
     private Buyer buyer;

    public BuyerInterests() {
    }

    public BuyerInterests(BuyerInterestsId id, Buyer buyer) {
       this.id = id;
       this.buyer = buyer;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="interests", column=@Column(name="interests", nullable=false) ) } )
    public BuyerInterestsId getId() {
        return this.id;
    }
    
    public void setId(BuyerInterestsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }




}


