package com.bookstore.entities;// default package
// Generated Aug 24, 2024, 4:07:45 PM by Hibernate Tools 6.5.2.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="bookstore"
)
public class Category  implements java.io.Serializable {


     private int categoryId;
     private String name;
     private String description;
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(int categoryId, String name) {
        this.categoryId = categoryId;
        this.name = name;
    }
    public Category(int categoryId, String name, String description, Set<Product> products) {
       this.categoryId = categoryId;
       this.name = name;
       this.description = description;
       this.products = products;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="category_id", unique=true, nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="name", nullable=false, length=255)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="category_has_products", catalog="bookstore", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=true) }, inverseJoinColumns = {
        @JoinColumn(name="product_id", nullable=false, updatable=true) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


