package com.bookstore.entities;// default package
// Generated Aug 24, 2024, 4:07:45 PM by Hibernate Tools 6.5.2.Final


import jakarta.persistence.*;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name="order"
    ,catalog="bookstore"
)
public class Order  implements java.io.Serializable {


     private int orderId;
     private Buyer buyer;
     private Date date;
     private Set<OrderHasProducts> orderHasProductses = new HashSet<OrderHasProducts>(0);

    public Order() {
    }

	
    public Order(int orderId, Date date) {
        this.orderId = orderId;
        this.date = date;
    }
    public Order(int orderId, Buyer buyer, Date date, Set<OrderHasProducts> orderHasProductses) {
       this.orderId = orderId;
       this.buyer = buyer;
       this.date = date;
       this.orderHasProductses = orderHasProductses;
    }
   
     @Id 

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="order_id", unique=true, nullable=false)
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="id" , nullable=false)
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="order")
    public Set<OrderHasProducts> getOrderHasProductses() {
        return this.orderHasProductses;
    }
    
    public void setOrderHasProductses(Set<OrderHasProducts> orderHasProductses) {
        this.orderHasProductses = orderHasProductses;
    }




}


