// default package
// Generated Aug 23, 2024, 4:18:42 PM by Hibernate Tools 6.5.2.Final
package entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Table(name="buyer"
    ,catalog="ecommerce"
)
public class Buyer  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String password;
     private Date birthday;
     private int building;
     private String street;
     private String city;
     private String phone;
     private float cardLimit;
     private String jop;
     private Set<BuyerChosenProducts> buyerChosenProductses = new HashSet<BuyerChosenProducts>(0);
     private Set<Order> orders = new HashSet<Order>(0);
     private Set<BuyerInterests> buyerInterestses = new HashSet<BuyerInterests>(0);

    public Buyer() {
    }

	
    public Buyer(int id, String name, String email, String password, Date birthday, int building, String street, String city, String phone, float cardLimit, String jop) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.birthday = birthday;
        this.building = building;
        this.street = street;
        this.city = city;
        this.phone = phone;
        this.cardLimit = cardLimit;
        this.jop = jop;
    }
    public Buyer(int id, String name, String email, String password, Date birthday, int building, String street, String city, String phone, float cardLimit, String jop, Set<BuyerChosenProducts> buyerChosenProductses, Set<Order> orders, Set<BuyerInterests> buyerInterestses) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
       this.birthday = birthday;
       this.building = building;
       this.street = street;
       this.city = city;
       this.phone = phone;
       this.cardLimit = cardLimit;
       this.jop = jop;
       this.buyerChosenProductses = buyerChosenProductses;
       this.orders = orders;
       this.buyerInterestses = buyerInterestses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", nullable=false, length=10)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="building", nullable=false)
    public int getBuilding() {
        return this.building;
    }
    
    public void setBuilding(int building) {
        this.building = building;
    }

    
    @Column(name="street", nullable=false, length=200)
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }

    
    @Column(name="city", nullable=false, length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="phone", nullable=false, length=15)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="card_limit", nullable=false, precision=12)
    public float getCardLimit() {
        return this.cardLimit;
    }
    
    public void setCardLimit(float cardLimit) {
        this.cardLimit = cardLimit;
    }

    
    @Column(name="jop", nullable=false, length=50)
    public String getJop() {
        return this.jop;
    }
    
    public void setJop(String jop) {
        this.jop = jop;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buyer")
    public Set<BuyerChosenProducts> getBuyerChosenProductses() {
        return this.buyerChosenProductses;
    }
    
    public void setBuyerChosenProductses(Set<BuyerChosenProducts> buyerChosenProductses) {
        this.buyerChosenProductses = buyerChosenProductses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buyer")
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="buyer")
    public Set<BuyerInterests> getBuyerInterestses() {
        return this.buyerInterestses;
    }
    
    public void setBuyerInterestses(Set<BuyerInterests> buyerInterestses) {
        this.buyerInterestses = buyerInterestses;
    }




}


