// default package
// Generated Aug 23, 2024, 4:18:42 PM by Hibernate Tools 6.5.2.Final
package entities;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * BuyerChosenProducts generated by hbm2java
 */
@Entity
@Table(name="buyer_chosen_products"
    ,catalog="ecommerce"
)
public class BuyerChosenProducts  implements java.io.Serializable {


     private BuyerChosenProductsId id;
     private Buyer buyer;
     private Product product;
     private int quantity;

    public BuyerChosenProducts() {
    }

    public BuyerChosenProducts(BuyerChosenProductsId id, Buyer buyer, Product product, int quantity) {
       this.id = id;
       this.buyer = buyer;
       this.product = product;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="id", column=@Column(name="id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public BuyerChosenProductsId getId() {
        return this.id;
    }
    
    public void setId(BuyerChosenProductsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id", nullable=false, insertable=false, updatable=false)
    public Buyer getBuyer() {
        return this.buyer;
    }
    
    public void setBuyer(Buyer buyer) {
        this.buyer = buyer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


