// default package
// Generated Aug 23, 2024, 4:18:42 PM by Hibernate Tools 6.5.2.Final

package entities;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="ecommerce"
)
public class Category  implements java.io.Serializable {


     private int categoryId;
     private String name;
     private String descreption;
     private Set<Product> products = new HashSet<Product>(0);

    public Category() {
    }

	
    public Category(int categoryId, String name, String descreption) {
        this.categoryId = categoryId;
        this.name = name;
        this.descreption = descreption;
    }
    public Category(int categoryId, String name, String descreption, Set<Product> products) {
       this.categoryId = categoryId;
       this.name = name;
       this.descreption = descreption;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="category_id", unique=true, nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="descreption", nullable=false, length=300)
    public String getDescreption() {
        return this.descreption;
    }
    
    public void setDescreption(String descreption) {
        this.descreption = descreption;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="category_has_products", catalog="ecommerce", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="product_id", nullable=false, updatable=false) })
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


