// default package
// Generated Aug 23, 2024, 4:18:42 PM by Hibernate Tools 6.5.2.Final
package entities;

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * OrderHasProducts generated by hbm2java
 */
@Entity
@Table(name="order_has_products"
    ,catalog="ecommerce"
)
public class OrderHasProducts  implements java.io.Serializable {


     private OrderHasProductsId id;
     private Order order;
     private Product product;
     private int quantity;
     private float price;

    public OrderHasProducts() {
    }

    public OrderHasProducts(OrderHasProductsId id, Order order, Product product, int quantity, float price) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="order_id", nullable=false) ), 
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ) } )
    public OrderHasProductsId getId() {
        return this.id;
    }
    
    public void setId(OrderHasProductsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false, insertable=false, updatable=false)
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=12)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }




}


