// default package
// Generated Aug 23, 2024, 4:18:42 PM by Hibernate Tools 6.5.2.Final
package entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="ecommerce"
)
public class Product  implements java.io.Serializable {


     private int productId;
     private String name;
     private String description;
     private float price;
     private String imagesPath;
     private int stockQuantity;
     private String author;
     private Date publishDate;
     private int pages;
     private int avaliblity;
     private Set<BuyerChosenProducts> buyerChosenProductses = new HashSet<BuyerChosenProducts>(0);
     private Set<OrderHasProducts> orderHasProductses = new HashSet<OrderHasProducts>(0);
     private Set<Category> categories = new HashSet<Category>(0);

    public Product() {
    }

	
    public Product(int productId, String name, String description, float price, String imagesPath, int stockQuantity, String author, Date publishDate, int pages, int avaliblity) {
        this.productId = productId;
        this.name = name;
        this.description = description;
        this.price = price;
        this.imagesPath = imagesPath;
        this.stockQuantity = stockQuantity;
        this.author = author;
        this.publishDate = publishDate;
        this.pages = pages;
        this.avaliblity = avaliblity;
    }
    public Product(int productId, String name, String description, float price, String imagesPath, int stockQuantity, String author, Date publishDate, int pages, int avaliblity, Set<BuyerChosenProducts> buyerChosenProductses, Set<OrderHasProducts> orderHasProductses, Set<Category> categories) {
       this.productId = productId;
       this.name = name;
       this.description = description;
       this.price = price;
       this.imagesPath = imagesPath;
       this.stockQuantity = stockQuantity;
       this.author = author;
       this.publishDate = publishDate;
       this.pages = pages;
       this.avaliblity = avaliblity;
       this.buyerChosenProductses = buyerChosenProductses;
       this.orderHasProductses = orderHasProductses;
       this.categories = categories;
    }
   
     @Id 

    
    @Column(name="product_id", unique=true, nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }

    
    @Column(name="name", nullable=false, length=300)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", nullable=false, length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", nullable=false, precision=12)
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }

    
    @Column(name="images_path", nullable=false, length=500)
    public String getImagesPath() {
        return this.imagesPath;
    }
    
    public void setImagesPath(String imagesPath) {
        this.imagesPath = imagesPath;
    }

    
    @Column(name="stock_quantity", nullable=false)
    public int getStockQuantity() {
        return this.stockQuantity;
    }
    
    public void setStockQuantity(int stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    
    @Column(name="author", nullable=false, length=200)
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="publish_date", nullable=false, length=10)
    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    
    @Column(name="pages", nullable=false)
    public int getPages() {
        return this.pages;
    }
    
    public void setPages(int pages) {
        this.pages = pages;
    }

    
    @Column(name="avaliblity", nullable=false)
    public int getAvaliblity() {
        return this.avaliblity;
    }
    
    public void setAvaliblity(int avaliblity) {
        this.avaliblity = avaliblity;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<BuyerChosenProducts> getBuyerChosenProductses() {
        return this.buyerChosenProductses;
    }
    
    public void setBuyerChosenProductses(Set<BuyerChosenProducts> buyerChosenProductses) {
        this.buyerChosenProductses = buyerChosenProductses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="product")
    public Set<OrderHasProducts> getOrderHasProductses() {
        return this.orderHasProductses;
    }
    
    public void setOrderHasProductses(Set<OrderHasProducts> orderHasProductses) {
        this.orderHasProductses = orderHasProductses;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


